//
// Autogenerated by Thrift Compiler (0.13.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = require('./nested_types');
//HELPER FUNCTIONS AND STRUCTURES

var ProperlyNested_ping_args = function(args) {
};
ProperlyNested_ping_args.prototype = {};
ProperlyNested_ping_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ProperlyNested_ping_args.prototype.write = function(output) {
  output.writeStructBegin('ProperlyNested_ping_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ProperlyNested_ping_result = function(args) {
};
ProperlyNested_ping_result.prototype = {};
ProperlyNested_ping_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ProperlyNested_ping_result.prototype.write = function(output) {
  output.writeStructBegin('ProperlyNested_ping_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ProperlyNested_is_properly_nested_args = function(args) {
  this.w = null;
  if (args) {
    if (args.w !== undefined && args.w !== null) {
      this.w = new ttypes.Work(args.w);
    }
  }
};
ProperlyNested_is_properly_nested_args.prototype = {};
ProperlyNested_is_properly_nested_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.w = new ttypes.Work();
        this.w.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ProperlyNested_is_properly_nested_args.prototype.write = function(output) {
  output.writeStructBegin('ProperlyNested_is_properly_nested_args');
  if (this.w !== null && this.w !== undefined) {
    output.writeFieldBegin('w', Thrift.Type.STRUCT, 1);
    this.w.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ProperlyNested_is_properly_nested_result = function(args) {
  this.success = null;
  this.fail = null;
  if (args instanceof ttypes.InvalidStringError) {
    this.fail = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
    if (args.fail !== undefined && args.fail !== null) {
      this.fail = args.fail;
    }
  }
};
ProperlyNested_is_properly_nested_result.prototype = {};
ProperlyNested_is_properly_nested_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.fail = new ttypes.InvalidStringError();
        this.fail.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ProperlyNested_is_properly_nested_result.prototype.write = function(output) {
  output.writeStructBegin('ProperlyNested_is_properly_nested_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  if (this.fail !== null && this.fail !== undefined) {
    output.writeFieldBegin('fail', Thrift.Type.STRUCT, 1);
    this.fail.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ProperlyNested_puts_io_args = function(args) {
  this.printable = null;
  if (args) {
    if (args.printable !== undefined && args.printable !== null) {
      this.printable = args.printable;
    }
  }
};
ProperlyNested_puts_io_args.prototype = {};
ProperlyNested_puts_io_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.printable = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ProperlyNested_puts_io_args.prototype.write = function(output) {
  output.writeStructBegin('ProperlyNested_puts_io_args');
  if (this.printable !== null && this.printable !== undefined) {
    output.writeFieldBegin('printable', Thrift.Type.STRING, 1);
    output.writeString(this.printable);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ProperlyNested_puts_io_result = function(args) {
};
ProperlyNested_puts_io_result.prototype = {};
ProperlyNested_puts_io_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ProperlyNested_puts_io_result.prototype.write = function(output) {
  output.writeStructBegin('ProperlyNested_puts_io_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ProperlyNestedClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
ProperlyNestedClient.prototype = {};
ProperlyNestedClient.prototype.seqid = function() { return this._seqid; };
ProperlyNestedClient.prototype.new_seqid = function() { return this._seqid += 1; };

ProperlyNestedClient.prototype.ping = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ping();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ping();
  }
};

ProperlyNestedClient.prototype.send_ping = function() {
  var output = new this.pClass(this.output);
  var args = new ProperlyNested_ping_args();
  try {
    output.writeMessageBegin('ping', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

ProperlyNestedClient.prototype.recv_ping = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ProperlyNested_ping_result();
  result.read(input);
  input.readMessageEnd();

  callback(null);
};

ProperlyNestedClient.prototype.is_properly_nested = function(w, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_is_properly_nested(w);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_is_properly_nested(w);
  }
};

ProperlyNestedClient.prototype.send_is_properly_nested = function(w) {
  var output = new this.pClass(this.output);
  var params = {
    w: w
  };
  var args = new ProperlyNested_is_properly_nested_args(params);
  try {
    output.writeMessageBegin('is_properly_nested', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

ProperlyNestedClient.prototype.recv_is_properly_nested = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ProperlyNested_is_properly_nested_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.fail) {
    return callback(result.fail);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('is_properly_nested failed: unknown result');
};

ProperlyNestedClient.prototype.puts_io = function(printable, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_puts_io(printable);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_puts_io(printable);
  }
};

ProperlyNestedClient.prototype.send_puts_io = function(printable) {
  var output = new this.pClass(this.output);
  var params = {
    printable: printable
  };
  var args = new ProperlyNested_puts_io_args(params);
  try {
    output.writeMessageBegin('puts_io', Thrift.MessageType.ONEWAY, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    this.output.flush();
    var callback = this._reqs[this.seqid()] || function() {};
    delete this._reqs[this.seqid()];
    callback(null);
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};
var ProperlyNestedProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
ProperlyNestedProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
ProperlyNestedProcessor.prototype.process_ping = function(seqid, input, output) {
  var args = new ProperlyNested_ping_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ping.length === 0) {
    Q.fcall(this._handler.ping.bind(this._handler)
    ).then(function(result) {
      var result_obj = new ProperlyNested_ping_result({success: result});
      output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("ping", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.ping(function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new ProperlyNested_ping_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("ping", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
ProperlyNestedProcessor.prototype.process_is_properly_nested = function(seqid, input, output) {
  var args = new ProperlyNested_is_properly_nested_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.is_properly_nested.length === 1) {
    Q.fcall(this._handler.is_properly_nested.bind(this._handler),
      args.w
    ).then(function(result) {
      var result_obj = new ProperlyNested_is_properly_nested_result({success: result});
      output.writeMessageBegin("is_properly_nested", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      if (err instanceof ttypes.InvalidStringError) {
        result = new ProperlyNested_is_properly_nested_result(err);
        output.writeMessageBegin("is_properly_nested", Thrift.MessageType.REPLY, seqid);
      } else {
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("is_properly_nested", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.is_properly_nested(args.w, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof ttypes.InvalidStringError) {
        result_obj = new ProperlyNested_is_properly_nested_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("is_properly_nested", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("is_properly_nested", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
ProperlyNestedProcessor.prototype.process_puts_io = function(seqid, input, output) {
  var args = new ProperlyNested_puts_io_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.puts_io(args.printable);
};
